var annotated =
[
    [ "SteamVdfParse", "db/d3c/namespace_steam_vdf_parse.html", "db/d3c/namespace_steam_vdf_parse" ],
    [ "AddGameWizard", "d5/d20/class_add_game_wizard.html", "d5/d20/class_add_game_wizard" ],
    [ "AscensionDialog", "d1/d10/class_ascension_dialog.html", "d1/d10/class_ascension_dialog" ],
    [ "BorderlessWindow", "d2/d4b/class_borderless_window.html", "d2/d4b/class_borderless_window" ],
    [ "Database", "dc/d83/class_database.html", "dc/d83/class_database" ],
    [ "DRMPage", "d8/d67/class_d_r_m_page.html", "d8/d67/class_d_r_m_page" ],
    [ "DRMSetupWizard", "da/dfa/class_d_r_m_setup_wizard.html", "da/dfa/class_d_r_m_setup_wizard" ],
    [ "FinalPage", "da/d80/class_final_page.html", "da/d80/class_final_page" ],
    [ "Game", "dd/db8/struct_game.html", "dd/db8/struct_game" ],
    [ "InfoPage", "d8/d44/class_info_page.html", "d8/d44/class_info_page" ],
    [ "InitPage", "d1/df5/class_init_page.html", "d1/df5/class_init_page" ],
    [ "IntroPage", "d3/d3c/class_intro_page.html", "d3/d3c/class_intro_page" ],
    [ "LastPage", "d0/d42/class_last_page.html", "d0/d42/class_last_page" ],
    [ "Library", "d7/d55/class_library.html", "d7/d55/class_library" ],
    [ "MainPanel", "d1/d88/class_main_panel.html", "d1/d88/class_main_panel" ],
    [ "News", "db/d2d/class_news.html", "db/d2d/class_news" ],
    [ "NewsFeedWidget", "d7/dbd/class_news_feed_widget.html", "d7/dbd/class_news_feed_widget" ],
    [ "QWinHost", "d5/d3a/class_q_win_host.html", "d5/d3a/class_q_win_host" ],
    [ "QWinWidget", "d5/d79/class_q_win_widget.html", "d5/d79/class_q_win_widget" ],
    [ "ResultsPage", "d6/dfc/class_results_page.html", "d6/dfc/class_results_page" ],
    [ "Settings", "db/d2b/class_settings.html", "db/d2b/class_settings" ],
    [ "Sidebar", "df/d42/class_sidebar.html", "df/d42/class_sidebar" ],
    [ "TabWidget", "d6/dc8/class_tab_widget.html", "d6/dc8/class_tab_widget" ],
    [ "UnixPanel", "de/d68/class_unix_panel.html", "de/d68/class_unix_panel" ],
    [ "UnixWindow", "d2/d2b/class_unix_window.html", "d2/d2b/class_unix_window" ],
    [ "WinPanel", "d6/d55/class_win_panel.html", "d6/d55/class_win_panel" ],
    [ "WinWindow", "d8/db8/class_win_window.html", "d8/db8/class_win_window" ]
];